# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/data_mem_ooc.xdc

# XDC: C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/dont_touch.xdc

# XDC: C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/ins_mem_ooc.xdc

# IP: ip/ins_mem_2/ins_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ins_mem || ORIG_REF_NAME==ins_mem} -quiet] -quiet

# IP: ip/data_mem_1/data_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# XDC: ip/ins_mem_2/ins_mem_ooc.xdc

# XDC: ip/data_mem_1/data_mem_ooc.xdc
