# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.runs/synth_1/RISC_Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.3 [current_project]
set_property ip_output_repo {c:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/ALU.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/ALUControl.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder2.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder3.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder4.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder_C.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Adder_U.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Buffer.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Buffer_temp.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Ch.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/ControlUnit.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Controller.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Counter_offset.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Delta0.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Delta1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/FSM_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Imm_Gen.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/MUX2to1_PC.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Maj.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux2to1_ALU.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux2to1_WB.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux32.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_AES1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_AES2.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_Buffer.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_J1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_J2.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_U1_type.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_U2_type.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_data.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_ins.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Mux_res_sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/PC.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Parise_mux.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Plus_4.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg0.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg10.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg11.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg12.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg13.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg14.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg15.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg1_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg2.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg2_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg3.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg32.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg3_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg4.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg4_Sha.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg5.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg6.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg7.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg8.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg9.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/RegI.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_A.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_B.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_C.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_D.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_E.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_F.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_G.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_H.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_J.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_K.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Reg_res256.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Registers_file.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Sigma0.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Sigma1.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/wr_b2data.v}
  {C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Source/Top.v}
}
read_ip -quiet {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.srcs/sources_1/ip/ins_mem_2/ins_mem.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.srcs/sources_1/ip/ins_mem_2/ins_mem_ooc.xdc}}]

read_ip -quiet {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.srcs/sources_1/ip/data_mem_1/data_mem.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/RV_Sha256_Send2Dat.srcs/sources_1/ip/data_mem_1/data_mem_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/data_mem_ooc.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/data_mem_ooc.xdc}}]

read_xdc {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/dont_touch.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/dont_touch.xdc}}]

read_xdc {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/ins_mem_ooc.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Dat Pham/Downloads/RV_Sha245_SendtoDat/Vivado/ins_mem_ooc.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RISC_Top -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISC_Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISC_Top_utilization_synth.rpt -pb RISC_Top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
