# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ins_mem_2/ins_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ins_mem || ORIG_REF_NAME==ins_mem} -quiet] -quiet

# IP: ip/data_mem_1/data_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# XDC: ip/ins_mem_2/ins_mem_ooc.xdc

# XDC: ip/data_mem_1/data_mem_ooc.xdc
